In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.colors import LogNorm, Normalize
import seaborn as sns
import glob
import scienceplots
plt.style.use(['science','nature'])
plt.rc('axes', labelsize=11)
plt.rc('xtick', labelsize=12)
plt.rc('ytick', labelsize=12)
plt.rc('legend', fontsize=11)

In [2]:
datas,file=[],[]
for i in np.sort(glob.glob("Results/*.csv")):
    #print(i)
    dat=pd.read_csv(i)
    datas.append(dat)
    file.append(i)

In [3]:
print("Realizados {} experimentos ({}%)".format(len(datas),np.round(len(datas)/(180+90)*100,2)))
df=pd.concat(datas)
df["File"]=file
print(f"Total filas: {len(df)}")  # debería ser 180

# Verificar duplicados
dups = df.duplicated(subset=["min_magn","n_qubits","reps","n_train_quantum"])
print(f"Duplicados: {dups.sum()}")  # debería ser 0

# Ver parámetros únicos
print(df["min_magn"].value_counts().sort_index())
print(df["n_train_quantum"].value_counts().sort_index())
df.to_csv("AllExperiments.csv")

Realizados 270 experimentos (100.0%)
Total filas: 270
Duplicados: 90
min_magn
0.0    45
3.0    45
4.0    45
5.0    45
6.0    45
7.0    45
Name: count, dtype: int64
n_train_quantum
50     54
51     36
70     36
97     36
100    27
150    27
160    18
200    18
250    18
Name: count, dtype: int64

In [4]:
df[df["acc_qsvm"]>df["acc_rbf_sub"]]

,n_total,n_fd,n_nofd,n_train_full,n_train_quantum,n_test,n_qubits,reps,C,min_magn,auc_rbf_full,acc_rbf_full,auc_rbf_sub,acc_rbf_sub,auc_qsvm,acc_qsvm,delta_auc_fair,delta_auc_full,File
0,380,190,190,285,50,95,4,1,1.0,3.0,0.924202,0.905263,0.907358,0.863158,0.864362,0.873684,-0.042996,-0.059840,Results/exp_3.0_4_1_50.csv
0,380,190,190,285,50,95,4,3,1.0,3.0,0.924202,0.905263,0.907358,0.863158,0.877216,0.873684,-0.030142,-0.046986,Results/exp_3.0_4_3_50.csv
0,380,190,190,285,100,95,6,1,1.0,3.0,0.917996,0.884211,0.912677,0.863158,0.872784,0.873684,-0.039894,-0.045213,Results/exp_3.0_6_1_100.csv
0,380,190,190,285,50,95,6,1,1.0,3.0,0.917996,0.884211,0.916223,0.842105,0.881649,0.873684,-0.034574,-0.036348,Results/exp_3.0_6_1_50.csv
0,380,190,190,285,100,95,6,2,1.0,3.0,0.917996,0.884211,0.912677,0.863158,0.909131,0.873684,-0.003546,-0.008865,Results/exp_3.0_6_2_100.csv
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,68,34,34,51,51,17,8,3,1.0,7.0,0.930556,0.823529,0.930556,0.823529,0.916667,0.941176,-0.013889,-0.013889,Results/exp_7.0_8_3_100.csv
0,68,34,34,51,51,17,8,3,1.0,7.0,0.930556,0.823529,0.930556,0.823529,0.916667,0.941176,-0.013889,-0.013889,Results/exp_7.0_8_3_150.csv
0,68,34,34,51,51,17,8,3,1.0,7.0,0.930556,0.823529,0.930556,0.823529,0.916667,0.941176,-0.013889,-0.013889,Results/exp_7.0_8_3_200.csv
0,68,34,34,51,51,17,8,3,1.0,7.0,0.930556,0.823529,0.930556,0.823529,0.916667,0.941176,-0.013889,-0.013889,Results/exp_7.0_8_3_250.csv
0,68,34,34,51,50,17,8,3,1.0,7.0,0.930556,0.823529,0.930556,0.823529,0.916667,0.941176,-0.013889,-0.013889,Results/exp_7.0_8_3_50.csv

In [5]:
df[df["acc_qsvm"]>df["acc_rbf_full"]]

,n_total,n_fd,n_nofd,n_train_full,n_train_quantum,n_test,n_qubits,reps,C,min_magn,auc_rbf_full,acc_rbf_full,auc_rbf_sub,acc_rbf_sub,auc_qsvm,acc_qsvm,delta_auc_fair,delta_auc_full,File
0,214,107,107,160,100,54,4,1,1.0,4.0,0.801097,0.777778,0.799726,0.759259,0.964335,0.907407,0.164609,0.163237,Results/exp_4.0_4_1_100.csv
0,214,107,107,160,150,54,4,1,1.0,4.0,0.801097,0.777778,0.801097,0.740741,0.954733,0.907407,0.153635,0.153635,Results/exp_4.0_4_1_150.csv
0,214,107,107,160,160,54,4,1,1.0,4.0,0.801097,0.777778,0.801097,0.777778,0.960219,0.907407,0.159122,0.159122,Results/exp_4.0_4_1_200.csv
0,214,107,107,160,160,54,4,1,1.0,4.0,0.801097,0.777778,0.801097,0.777778,0.960219,0.907407,0.159122,0.159122,Results/exp_4.0_4_1_250.csv
0,214,107,107,160,50,54,4,1,1.0,4.0,0.801097,0.777778,0.799726,0.870370,0.930041,0.888889,0.130316,0.128944,Results/exp_4.0_4_1_50.csv
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,68,34,34,51,51,17,8,3,1.0,7.0,0.930556,0.823529,0.930556,0.823529,0.916667,0.941176,-0.013889,-0.013889,Results/exp_7.0_8_3_100.csv
0,68,34,34,51,51,17,8,3,1.0,7.0,0.930556,0.823529,0.930556,0.823529,0.916667,0.941176,-0.013889,-0.013889,Results/exp_7.0_8_3_150.csv
0,68,34,34,51,51,17,8,3,1.0,7.0,0.930556,0.823529,0.930556,0.823529,0.916667,0.941176,-0.013889,-0.013889,Results/exp_7.0_8_3_200.csv
0,68,34,34,51,51,17,8,3,1.0,7.0,0.930556,0.823529,0.930556,0.823529,0.916667,0.941176,-0.013889,-0.013889,Results/exp_7.0_8_3_250.csv
0,68,34,34,51,50,17,8,3,1.0,7.0,0.930556,0.823529,0.930556,0.823529,0.916667,0.941176,-0.013889,-0.013889,Results/exp_7.0_8_3_50.csv

In [6]:
df[df["auc_qsvm"]>df["auc_rbf_sub"]]

,n_total,n_fd,n_nofd,n_train_full,n_train_quantum,n_test,n_qubits,reps,C,min_magn,auc_rbf_full,acc_rbf_full,auc_rbf_sub,acc_rbf_sub,auc_qsvm,acc_qsvm,delta_auc_fair,delta_auc_full,File
0,380,190,190,285,150,95,4,2,1.0,3.0,0.924202,0.905263,0.920656,0.894737,0.927748,0.873684,0.007092,0.003546,Results/exp_3.0_4_2_150.csv
0,380,190,190,285,150,95,4,3,1.0,3.0,0.924202,0.905263,0.920656,0.894737,0.935727,0.884211,0.015071,0.011525,Results/exp_3.0_4_3_150.csv
0,380,190,190,285,100,95,8,2,1.0,3.0,0.917553,0.884211,0.907358,0.852632,0.911348,0.873684,0.003989,-0.006206,Results/exp_3.0_8_2_100.csv
0,380,190,190,285,200,95,8,3,1.0,3.0,0.917553,0.884211,0.902926,0.873684,0.916667,0.873684,0.013741,-0.000887,Results/exp_3.0_8_3_200.csv
0,214,107,107,160,100,54,4,1,1.0,4.0,0.801097,0.777778,0.799726,0.759259,0.964335,0.907407,0.164609,0.163237,Results/exp_4.0_4_1_100.csv
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,68,34,34,51,51,17,8,2,1.0,7.0,0.930556,0.823529,0.930556,0.823529,1.000000,0.941176,0.069444,0.069444,Results/exp_7.0_8_2_100.csv
0,68,34,34,51,51,17,8,2,1.0,7.0,0.930556,0.823529,0.930556,0.823529,1.000000,0.941176,0.069444,0.069444,Results/exp_7.0_8_2_150.csv
0,68,34,34,51,51,17,8,2,1.0,7.0,0.930556,0.823529,0.930556,0.823529,1.000000,0.941176,0.069444,0.069444,Results/exp_7.0_8_2_200.csv
0,68,34,34,51,51,17,8,2,1.0,7.0,0.930556,0.823529,0.930556,0.823529,1.000000,0.941176,0.069444,0.069444,Results/exp_7.0_8_2_250.csv
0,68,34,34,51,50,17,8,2,1.0,7.0,0.930556,0.823529,0.930556,0.823529,1.000000,0.941176,0.069444,0.069444,Results/exp_7.0_8_2_50.csv

In [7]:
df[df["auc_qsvm"]>df["auc_rbf_full"]]

,n_total,n_fd,n_nofd,n_train_full,n_train_quantum,n_test,n_qubits,reps,C,min_magn,auc_rbf_full,acc_rbf_full,auc_rbf_sub,acc_rbf_sub,auc_qsvm,acc_qsvm,delta_auc_fair,delta_auc_full,File
0,380,190,190,285,150,95,4,2,1.0,3.0,0.924202,0.905263,0.920656,0.894737,0.927748,0.873684,0.007092,0.003546,Results/exp_3.0_4_2_150.csv
0,380,190,190,285,150,95,4,3,1.0,3.0,0.924202,0.905263,0.920656,0.894737,0.935727,0.884211,0.015071,0.011525,Results/exp_3.0_4_3_150.csv
0,214,107,107,160,100,54,4,1,1.0,4.0,0.801097,0.777778,0.799726,0.759259,0.964335,0.907407,0.164609,0.163237,Results/exp_4.0_4_1_100.csv
0,214,107,107,160,150,54,4,1,1.0,4.0,0.801097,0.777778,0.801097,0.740741,0.954733,0.907407,0.153635,0.153635,Results/exp_4.0_4_1_150.csv
0,214,107,107,160,160,54,4,1,1.0,4.0,0.801097,0.777778,0.801097,0.777778,0.960219,0.907407,0.159122,0.159122,Results/exp_4.0_4_1_200.csv
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,68,34,34,51,51,17,8,2,1.0,7.0,0.930556,0.823529,0.930556,0.823529,1.000000,0.941176,0.069444,0.069444,Results/exp_7.0_8_2_100.csv
0,68,34,34,51,51,17,8,2,1.0,7.0,0.930556,0.823529,0.930556,0.823529,1.000000,0.941176,0.069444,0.069444,Results/exp_7.0_8_2_150.csv
0,68,34,34,51,51,17,8,2,1.0,7.0,0.930556,0.823529,0.930556,0.823529,1.000000,0.941176,0.069444,0.069444,Results/exp_7.0_8_2_200.csv
0,68,34,34,51,51,17,8,2,1.0,7.0,0.930556,0.823529,0.930556,0.823529,1.000000,0.941176,0.069444,0.069444,Results/exp_7.0_8_2_250.csv
0,68,34,34,51,50,17,8,2,1.0,7.0,0.930556,0.823529,0.930556,0.823529,1.000000,0.941176,0.069444,0.069444,Results/exp_7.0_8_2_50.csv